export const FETCH_PRODUCTS_GET = "FETCH_PRODUCTS_GET";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";

export const FETCH_TEACHERS_GET = "FETCH_TEACHERS_GET";
export const FETCH_TEACHERS_SUCCESS = "FETCH_TEACHERS_SUCCESS";
export const FETCH_TEACHERS_FAILED = "ETCH_TEACHERS_FAILED";
