import teacher1Avatar from "../assets/Teacher/image/teacher-image/teacher-1.jpg";
import teacher1Vedio from "../assets/Teacher/videos/teacher-1.mp4";
export const Teachers = [
  {
    id: 1,
    name: "name1 fammily1",
    language: "انگلیسی",
    lang: "use",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    decription: "اطلاعات مدرس",
    srcVedio: teacher1Vedio,
    srcPhoto: teacher1Avatar,
  },
  {
    id: 2,
    name: "name1 fammily1",
    language: "انگلیسی",
    lang: "use",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    decription: "اطلاعات مدرس",
    srcVedio: teacher1Vedio,
    srcPhoto: teacher1Avatar,
  },
  {
    id: 3,
    name: "name1 fammily1",
    language: "انگلیسی",
    lang: "use",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    decription: "اطلاعات مدرس",
    srcVedio: teacher1Vedio,
    srcPhoto: teacher1Avatar,
  },
  {
    id: 4,
    name: "name1 fammily1",
    language: "انگلیسی",
    lang: "use",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    decription: "اطلاعات مدرس",
    srcVedio: teacher1Vedio,
    srcPhoto: teacher1Avatar,
  },
  {
    id: 5,
    name: "name1 fammily1",
    language: "انگلیسی",
    lang: "use",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    decription: "اطلاعات مدرس",
    srcVedio: teacher1Vedio,
    srcPhoto: teacher1Avatar,
  },
  {
    id: 6,
    name: "name1 fammily1",
    language: "انگلیسی",
    lang: "use",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    decription: "اطلاعات مدرس",
    srcVedio: teacher1Vedio,
    srcPhoto: teacher1Avatar,
  },
  {
    id: 7,
    name: "name1 fammily1",
    language: "انگلیسی",
    lang: "use",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    decription: "اطلاعات مدرس",
    srcVedio: teacher1Vedio,
    srcPhoto: teacher1Avatar,
  },
];
