export const Teachers = [
  {
    id: 1,
    name: "name1 fammily1",
    language: "انگلیسی",
    lang: "use",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
  },
  {
    id: 2,
    name: "name1 fammily1",
    language: "us",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
  },
  {
    id: 3,
    name: "name1 fammily1",
    language: "us",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
  },
  {
    id: 4,
    name: "name1 fammily1",
    language: "us",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
  },
  {
    id: 5,
    name: "name1 fammily1",
    language: "us",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
  },
  {
    id: 6,
    name: "name1 fammily1",
    language: "us",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
  },
  {
    id: 7,
    name: "name1 fammily1",
    language: "us",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
  },
  {
    id: 8,
    name: "name1 fammily1",
    language: "us",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
  },
  {
    id: 9,
    name: "name1 fammily1",
    language: "us",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
  },
  {
    id: 10,
    name: "name1 fammily1",
    language: "us",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
  },
  {
    id: 11,
    name: "name1 fammily1",
    language: "us",
    level: "متوسط",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
    testSession: "آزمایشی",
    onehourPriceSession: 100000,
    priceLevel: "رایگان",
    xpertise: "IELTS",
    Skills: "زبان عمومی ,IELTS,اسپیکینگ",
  },
];
